name: Build and deploy ASP.Net Core app to Azure Web App - biblioCSharp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore ./Server/Server.csproj

      - name: Build with dotnet
        run: dotnet build ./Server/Server.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish ./Server/Server.csproj -c Release -o "${{ github.workspace }}/publish" --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3D70BB3C80284E88A54A8A00F2D0B183 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0D289287E8E40E8822A21AF1FB68ABB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3B6953E2A8414FA49D6A4274F2CB4A7F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'biblioCSharp'
          slot-name: 'Production'
          package: ${{ github.workspace }}/publish
